### Load Libraries

In [1]:
import pandas as pd
import numpy as np

### Load Data

In [2]:
df = pd.read_csv("poly.csv")

In [3]:
df.head()

Experience  Salary
0           1   47000
1           2   52000
2           3   63000
3           4   84000
4           5  150000

### Split Data

In [4]:
X = df.drop('Salary', axis=1)
y = df['Salary']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)
print(X) # experience 
print(y) # Salary 


Shape of X =  (10, 1)
Shape of y =  (10,)
   Experience
0           1
1           2
2           3
3           4
4           5
5           6
6           7
7           8
8           9
9          10
0      47000
1      52000
2      63000
3      84000
4     150000
5     200000
6     270000
7     350000
8     600000
9    1000000
Name: Salary, dtype: int64


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)
print(X_test)
print(y_test)


Shape of X_train =  (8, 1)
Shape of y_train =  (8,)
Shape of X_test =  (2, 1)
Shape of y_test =  (2,)
   Experience
3           4
4           5
3     84000
4    150000
Name: Salary, dtype: int64


### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.87235674]
 [ 0.39652579]
 [ 0.71374643]
 [ 1.03096706]
 [-1.18957738]
 [-1.50679801]
 [ 0.07930516]
 [ 1.3481877 ]]


## Polynomial Linear Regression - ML Model Training

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [16]:
poly_reg = PolynomialFeatures(degree=4)  # Experience 2 if degree 2^0=1, 2^1=2,2^2=4
poly_reg.fit(X_train)
#X_train transfrom polynomial format  for training 
X_train_poly = poly_reg.transform(X_train)
#x_test trainsfer polynomial format for testing 
X_test_poly = poly_reg.transform(X_test)
print("withou polynomial transfer but features scaling include ")
print(X_train)
print("after polynomial transfer ")
print(X_train_poly)

print(X_test_poly)

withou polynomial transfer but features scaling include 
[[-0.87235674]
 [ 0.39652579]
 [ 0.71374643]
 [ 1.03096706]
 [-1.18957738]
 [-1.50679801]
 [ 0.07930516]
 [ 1.3481877 ]]
after polynomial transfer 
[[ 1.00000000e+00 -8.72356744e-01  7.61006289e-01 -6.63868969e-01
   5.79130572e-01]
 [ 1.00000000e+00  3.96525793e-01  1.57232704e-01  6.23468228e-02
   2.47221233e-02]
 [ 1.00000000e+00  7.13746427e-01  5.09433962e-01  3.63606670e-01
   2.59522962e-01]
 [ 1.00000000e+00  1.03096706e+00  1.06289308e+00  1.09580776e+00
   1.12974170e+00]
 [ 1.00000000e+00 -1.18957738e+00  1.41509434e+00 -1.68336421e+00
   2.00249199e+00]
 [ 1.00000000e+00 -1.50679801e+00  2.27044025e+00 -3.42109486e+00
   5.15489894e+00]
 [ 1.00000000e+00  7.93051586e-02  6.28930818e-03  4.98774582e-04
   3.95553973e-05]
 [ 1.00000000e+00  1.34818770e+00  1.81761006e+00  2.45047952e+00
   3.30370634e+00]]
[[ 1.         -0.55513611  0.3081761  -0.17107968  0.09497251]
 [ 1.         -0.23791548  0.05660377 -0.01346691  

In [11]:
X_train_poly.shape, X_test_poly.shape

((8, 3), (2, 3))

In [17]:
lr = LinearRegression()

lr.fit(X_train_poly, y_train)

LinearRegression()

In [18]:
print(X_test)
print(y_test)

[[-0.55513611]
 [-0.23791548]]
3     84000
4    150000
Name: Salary, dtype: int64


In [19]:
y_pred = lr.predict(X_test_poly)
y_pred

array([119871.4385742, 161184.2485184])

In [15]:
y_test

3     84000
4    150000
Name: Salary, dtype: int64

In [20]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

mse, rmse

(705923760.1520948, 26569.225810175478)