### Load Libraries

In [1]:
import pandas as pd

### Load Data

In [2]:
df = pd.read_csv('Position_Salaries.csv')

In [3]:
df.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

## Split Data

In [4]:
X = df.drop(['Position','Salary'], axis=1)
y = df['Salary']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (10, 1)
Shape of y =  (10,)


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (8, 1)
Shape of y_train =  (8,)
Shape of X_test =  (2, 1)
Shape of y_test =  (2,)


## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)
print(X_test_sc)

[[-0.55513611]
 [-0.23791548]]


## Support Vector Regression - ML Model Training

In [8]:
from sklearn.svm import SVR

In [9]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train_sc, y_train)
#svr_rbf.score(X_test, y_test)

SVR()

In [10]:
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train_sc, y_train)
#svr_linear.score(X_test, y_test)

SVR(kernel='linear')

In [17]:
svr_poly = SVR(kernel='poly',degree=5,)
svr_poly.fit(X_train_sc, y_train)
#svr_poly.score(X_test, y_test)

SVR(degree=5, kernel='poly')

## Predict the value

In [12]:
X_test_sc[0]

array([-0.55513611])

In [13]:
print(svr_linear.predict([X_test_sc[0]]))
print(svr_rbf.predict([X_test_sc[0]]))
print(svr_poly.predict([X_test_sc[0]]))
print(X_test)
print(y_test)

[174994.4654088]
[174996.93704182]
[174999.75066666]
   Level
3      4
4      5
3     80000
4    110000
Name: Salary, dtype: int64


In [14]:
y_pred = svr_linear.predict(X_test_sc)
y_pred

array([174994.4654088 , 174996.67924528])

In [18]:
h=svr_poly.predict(X_test_sc)
h

array([174999.05099115, 174999.9067006 ])

In [44]:
y_test

3     80000
4    110000
Name: Salary, dtype: int64

In [15]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  6624258385.608824
RMSE =  81389.54715200732
