In [1]:
import numpy as np

# Difference between List & numpy 

In [2]:
#List (memory Address)
l=['1','yu','90']
print(id(l[0]))
print(id(l[1]))
print(id(l[2]))


2611315676912
2609348563312
2609348563504


In [3]:
#numpy Array(memory Address) 
s=np.array(['1','yu','90'])
print(id(s[0]))
print(id(s[1]))
print(id(s[2]))

2609348322064
2609348322064
2609348322064


In [4]:
# memory size diference  
import sys
#list 
ll=[x for x in range(10000)]
print(sys.getsizeof(ll))
# numpy 
ss=np.array(ll)
print(sys.getsizeof(ss))


85176
40112


In [9]:
#time Complexiy
%timeit ll

%timeit ss



62.3 ns ± 2.71 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
50.5 ns ± 0.688 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# 1D & 2D array create

In [4]:
#one Dimension Array
s=np.array([10,12,15])
print(s)

#Two Dimension Array
s1=np.array([[10,12,15],[20,30,35]])
print(s1[0][0])
print(s1)
#An array class in Numpy is called as ndarray
print(type(s1))

[10 12 15]
10
[[10 12 15]
 [20 30 35]]
<class 'numpy.ndarray'>


# 3d or N Dimension array create 

In [2]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# widgets use 

In [13]:
import ipywidgets as wid
def ab(Choose=[]):
    s=np.array(Choose)
    print(s)
    
wid.interact(ab,Choose=['[10,12,15]','[20,30,40]']);

interactive(children=(Dropdown(description='Choose', options=('[10,12,15]', '[20,30,40]'), value='[10,12,15]')…

# Common Features(Numpy Array)

In [17]:
#one Dimension Array 
s=np.array([1,2,3,4])
print("dimension",s.ndim)
print("Shape",s.shape)
print("Size",s.size)
print("Length",len(s))
print("type",type(s))
#2 Dimension Array

print("................................................................")
s1=np.array([[1,2,3,4],[5,6,7,8]])
print("dimension",s1.ndim)
print("Shape",s1.shape)
print("Size",s1.size)
print("Length",len(s1))
print("type",type(s1))

#converet Data Type 
# s=s.astype(int)


dimension 1
Shape (4,)
Size 4
Length 4
type <class 'numpy.ndarray'>
................................................................
dimension 2
Shape (2, 4)
Size 8
Length 2
type <class 'numpy.ndarray'>


# Zero Matrix & perticular value input 

In [12]:
s1=np.zeros((1,2)) # 1=Row and 2=Column np.zeros(shape,dtype)
#s1=np.zeros((2,2), dtype=bool)
#s1=np.ones((1,2))
print(s1)
s1[0][0]=12 #replace value 
print(s1)
#3=row and 2=column and value=10 
s2=np.full((3,2),10) 
print(s2)

[[0. 0.]]
[[12.  0.]]
[[10 10]
 [10 10]
 [10 10]]


# Range Define (1D Array)

In [22]:
#Range define 
s3=np.arange(10,20) # s3 value is 10 to 19
print(s3)

#increase value with 5
s4=np.arange(10,50,5) # increase value 5
print(s4)

[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45]


# Range Define (2D Array)

In [2]:
#arange method use through two dimension Array 
#np.array([1st column ..[1st raw,2nd raw],2nd column...[fst row, 2nd row ]])

s5=np.array([[np.arange(10,20)],[np.arange(20,30)]])


#print(s5)

print(s5[0][0]) #1st row
#print(s5[1][0]) # 2nd row 

[10 11 12 13 14 15 16 17 18 19]


# random number generate 

In [6]:
#random number generate 
s6=np.random.randint(1,7) # one type of luddu game 
print(s6)


6


# How many row and column in our array 

In [7]:
#shape function that provide how amny row and column 
s7=np.array([[10,12,15],[20,30,35]])
print(s7.shape) # how many row and column 


(2, 3)


# Matrix Shape change

In [8]:
# if you want to change row and column so change it 
s7.shape=(3,2) 
print(s7)

[[10 12]
 [15 20]
 [30 35]]


# Linespace Function( start point , end point , how many number )

In [13]:
# restep set to True
print(np.linspace(2.0, 3.0, num=5), "\n")

[2.   2.25 2.5  2.75 3.  ] 



# Ravel Function 2d array convert into 1d array 

In [2]:
#shape function that provide how amny row and column 
a=np.array([[10,12,15],[20,30,35]])
print(a)
print(a.ravel())



[[10 12 15]
 [20 30 35]]
[10 12 15 20 30 35]


# Transpose Matrix

In [10]:
a=np.array([[10,12,15],[20,30,35]])
print(a.transpose())

[[10 20]
 [12 30]
 [15 35]]


# Maximum and minimum value return 1D and 2D array 

In [13]:
a=np.array([[10,40,15],[35,30,20]])
print(a.max())
print(a.min())
# row wise check & maximum value return 
print(a.max(axis=1))
# column wise check & maximum value return 
print(a.max(axis=0))

40
10
[40 35]
[35 40 20]


# Extra row Add (create Another row)

In [7]:
#another row add
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])

np.vstack((s8,s9)) # v=vertical wise add 


array([[10, 12, 15, 30],
       [20, 30, 40, 10]])

# fst row value and second row  Add

In [4]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])

np.column_stack((s8,s9))

array([[10, 20],
       [12, 30],
       [15, 40],
       [30, 10]])

# Extra row Add on the Same row

In [15]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
np.hstack((s8,s9)) # h=horizontal 

array([10, 12, 15, 30, 20, 30, 40, 10])

# Common Value Find and Differ value Find 

In [9]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
# common value find 
c=np.intersect1d(s8,s9)
print(c)
# differ value return( s8 wise search) 
c1=np.setdiff1d(s8,s9) # show s8 value that value not include in our s9
print(c1)

[10 30]
[20 40]


# Addition 1D Array 


In [10]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
# all value add in array 
np.sum((s8,s9)) #10+12+15+30+20+30+40+10

167

In [11]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
# column(fst column +snd column ) 
np.sum([s8,s9],axis=0)


array([30, 42, 55, 40])

In [12]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
#fst array row all add and secod array row all add
np.sum([s8,s9],axis=1)

array([ 67, 100])

In [18]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
# if you want to add/subtruct/multiple/devided extra value
s8=s8+1 # [10,12,15,30] +1   [11,13,16,31]
print(s8)


[11 13 16 31]


# Multiple(Dot) operation 

In [13]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
s8.T # transpose matrix
s9.T
np.dot(s8,s9)  #( 10*20 + 12*30+........)

1460

# without numpy function , Sum /Multification perform 
(Very Slow Performance )

In [20]:
s8=np.array([10,12,15,30])
s9=np.array([20,30,40,10])
z=[]
for x,y in zip(s8,s9):
       z.append(s8*s9)
print(z[0])

[200 360 600 300]


# Addition & Multification of Matrix 

In [25]:
t1=np.array([[4,3],[2,1]])
t2=np.array([[8,9],[1,1]])
#Add two Matrix 
print(t1+t2) 
# multiple two matrix
print(t1.dot(t2))  

[[12 12]
 [ 3  2]]


# Mean ,Mode &Std function Numpy 

In [14]:
s8=np.array([10,12,15,30])
#s8=np.array([[10,40,15],[35,30,20]])
#average value 
print(np.mean(s8))
# squere root 
print(np.sqrt(s8))
#Standerd Division 
print(np.std(s8))



16.75
[3.16227766 3.46410162 3.87298335 5.47722558]
7.854139036202504


# Linear Lgebra With Numpy 

Idempotent Matrix

In [64]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

Rank , Trace & Determinant Matrix 

In [28]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A ( 6+(-2)+7)
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0


Multiple(Complex number ).......................... 
(3 + 2i)(1 + 7i)	= 3×1 + 3×7i + 2i×1+ 2i×7i
 	= 3 + 21i + 2i + 14i2
 	= 3 + 21i + 2i − 14   (because i2 = −1)
 	= −11 + 23i

In [30]:
# Scalars
product = np.dot(5, 4)
print("Dot Product of scalar values  : ", product)
 # 1D array
vector_a = 3 + 2j
vector_b = 1 + 7j
 
product = np.dot(vector_a, vector_b)
print("Dot Product  : ", product)


Dot Product of scalar values  :  20
Dot Product  :  (-11+23j)


Inner Method (fst row multiple 2nd row (# 1*11+2*12, 1*13+2*14    3*11+4*12, 3*13+4*14 )

In [32]:
#inner Product 
a = np.array([[1,2], [3,4]]) 

print('Array a:') 
print (a )
b = np.array([[11, 12], [13, 14]]) 

print('Array b:') 
print( b) 

print('Inner product:') 
print(np.inner(a,b)) 

Array a:
[[1 2]
 [3 4]]
Array b:
[[11 12]
 [13 14]]
Inner product:
[[35 41]
 [81 95]]


# 3d Array Multification 

In [15]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(x)
y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(y)
print('Multiple result') 
print(np.matmul(x,y)) 


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Multiple result
[[[  7  10]
  [ 15  22]]

 [[ 67  78]
  [ 91 106]]]


Matmul Method 
# A = [[A00, A01],
     [A10, A11]]
     
B = [[B00, B01],
     [B10, B11]]

Then the product is calculated as shown below
A*B = [[(A00*B00 + A01*B10), (A00*B01 + A01*B11)],
       [(A10*B00 + A11+B10), (A10*B01 + A11*B11)]]

In [68]:
# Finding the matrix product
arr1 = np.array([[1, 2, 3], [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.array([[11, 12, 13], [14, 15, 16],
                 [17, 18, 19]])
  
matrix_product = np.matmul(arr1, arr2)
print("Matrix Product is ")
print(matrix_product)
print()
  
arr1 = np.array([[2,2],[3,3]])
arr2 = np.array([[1,2,3],[4,5,6]])
  
matrix_product = np.matmul(arr1, arr2)
print("Matrix Product is ")
print(matrix_product)
print()
  
arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[1,2],[4,6]])
  
matrix_product = np.matmul(arr1, arr2)
print("Matrix Product is ")
print(matrix_product)

Matrix Product is 
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]

Matrix Product is 
[[10 14 18]
 [15 21 27]]

Matrix Product is 
[[ 900 1400]
 [1900 3000]]


# Linear Equations ( 3x+y=9  x+2y=8)

In [33]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

# Inverse Matrix

In [34]:
#2*2 matrix inverse
a=np.array([[2,5],[1,3]])
np.linalg.inv(a)

array([[ 3., -5.],
       [-1.,  2.]])

In [35]:
#3*3 matrix inverse 
a=np.array([[1,2,-2],[-1,3,0],[0,-2,1]])
np.linalg.inv(a)

array([[3., 2., 6.],
       [1., 1., 2.],
       [2., 2., 5.]])

# Eigen value & Eigen Vector 

In [72]:
#Eigen value & Eigen vector  
a=np.array([[1,2,-2],[-1,3,0],[0,-2,1]])

eigen_value,eigen_vector=np.linalg.eig(a)

print("eigen value",eigen_value)
print("eigen vector",eigen_vector)


eigen value [2.4406197+1.56961032j 2.4406197-1.56961032j 0.1187606+0.j        ]
eigen vector [[-0.77208278+0.j         -0.77208278-0.j          0.75789789+0.j        ]
 [-0.15554655-0.43646062j -0.15554655+0.43646062j  0.26304579+0.j        ]
 [ 0.40059228+0.16947392j  0.40059228-0.16947392j  0.59699053+0.j        ]]


# what is the Difference between Numpy and Pandas 

# Pandas  Library Concept 

Series object create

In [1]:
import pandas as pd
#one dimensional array =Series object
s=pd.Series([15,'8',9,48])
print(s)
print(s[2]) # you have used list all the property 


0    15
1     8
2     9
3    48
dtype: object
9


Index convert to Label 

In [2]:
#index value change 
s=pd.Series([15,8,9,48],index=['a','b','c','d']) #,dtype=int,name='x')
print(s)

a    15
b     8
c     9
d    48
dtype: int64


# Series function copy part description

In [2]:
import numpy as np
r = np.array([1, 2])
ser = pd.Series(r, copy=True) # ! change original data 
ser.iloc[0] = 999
print(ser)
print(r)

0    999
1      2
dtype: int32
[1 2]


#dictionary through pandas

In [4]:
#dictionary through pandas
s=pd.Series({'k1':15,'k2':8,'k3':9,'k4':48})
print(s)
print(s['k3'])


k1    15
k2     8
k3     9
k4    48
dtype: int64
9


# operator use under series function

In [4]:
s=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(s[0:2])
print(s[s>2]) # oprator use 
print(s['c']==2) # oprator use 


a    1
b    2
dtype: int64
c    3
d    4
dtype: int64
False


#Numpy and Pandas Series 

In [52]:
s=pd.Series(np.arange(1,10))
#s=pd.Series(range(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

# Sets Operations

In [ ]:

a={1,2,4,5}
b={4,5,6,7}
#a.union(b) # union 
a.intersection(b) # 4 & 5 include (a and b both)
a.difference(b) #  1 & 2 ! include in a &b  

# add,subtruct,multiple ,division operation use(Series)

In [41]:
# sum of Series
s=pd.Series([15,8,9,48])
s1=pd.Series([2,4,6,8])
print(s+2) 
print(s+s1)
print(s*s1)


0    17
1    10
2    11
3    50
dtype: int64
0    17
1    12
2    15
3    56
dtype: int64
0     30
1     32
2     54
3    384
dtype: int64


#Mean,Mode,std 

In [75]:
s=pd.Series([15,8,9,48])
print(s.mean())
print(s.median()) #15,8,9,48 = 8,9,15,48  median find= (9+15)/2 =12
print(s.std())


20.0
12.0
18.920887928424502


DataFrame Create (Table create ---- Name fst column and mks 2nd column)

In [6]:
s=pd.DataFrame({"name":['som','som2','som3','som4','som5','som6','som7'],"mks":[12,16,15,85,89,55,57]})
#s=pd.DataFrame({"name":pd.Series([1,2,3]),"mks":pd.Series(np.arange(1,10))})
#s=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

print(s)
print(s.head()) # fst 5 data show
print(s.tail())
print(s.shape)
print(s.describe())

   name  mks
0   som   12
1  som2   16
2  som3   15
3  som4   85
4  som5   89
5  som6   55
6  som7   57
   name  mks
0   som   12
1  som2   16
2  som3   15
3  som4   85
4  som5   89
   name  mks
2  som3   15
3  som4   85
4  som5   89
5  som6   55
6  som7   57
(7, 2)
            mks
count   7.00000
mean   47.00000
std    33.12099
min    12.00000
25%    15.50000
50%    55.00000
75%    71.00000
max    89.00000


# Read CSV File (using Pandas)

In [2]:
# Read CSV File 
s3=pd.read_csv("bank_loan.csv")#,nrows=2,usecols=[0,1],skiprows=[0,1]) ##ss = pd.read_excel('a.xlsx', sheet_name='Sheet1')
#Series object print 
#s4=pd.read_csv("single.csv")
#print(s3.iloc[0:2,0:2]) # 2 row and 2 column(index wise) read 
#Directory Find 
#import os
#print(os.getcwd())
s3



id     Balnc  Monthly_Credit Loan_Eli  Loan_Limit         Act_type
0    1   50000.0           10000       NO           0           Normal
1    2   60000.0           10000       NO           0           Normal
2    3   44545.0           13000       NO           0           Normal
3    4   20000.0           11000       NO           0           Normal
4    5  100000.0           20000      YES       50000           Salary
5    6  500000.0           25000      YES      200000           Salary
6    7  700000.0           35000      YES      400000        Bussiness
7    8    5000.0               0       NO           0           Normal
8    9   50000.0           10000       NO           0           Normal
9   10   60000.0           10000       NO           0           Normal
10  11   44545.0           13000       NO           0           Normal
11  12   20000.0           11000       NO           0           Normal
12  13   44545.0           20000      YES       50000           Salary
13  14   20000.0           25000      YES      200000           Salary
14  15  100000.0           35000      YES      400000        Bussiness
15  16    1000.0               0       NO           0  Student_account
16  17     500.0               0       NO           0  Student_account
17  18       NaN               0       NO           0  Student_account

# index change ,heder ,prefix & names use

In [3]:

s4=pd.read_csv("bank_loan.csv",index_col=['Act_type'])
#s5=pd.read_csv("bank_loan.csv",header=11) # perticular row convert into header 
#s6=pd.read_csv("bank_loan.csv",header=None) # NO Header 
#your choice name as a header 
#s6=pd.read_csv("bank_loan.csv",header=None,prefix='col') # column name prefix wise 
#s6=pd.read_csv("bank_loan.csv",names=['A','B','C','D','E','F']) # different different column name define 
s6

col0    col1            col2           col3        col4             col5
0    id   Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
1     1   50000           10000             NO           0           Normal
2     2   60000           10000             NO           0           Normal
3     3   44545           13000             NO           0           Normal
4     4   20000           11000             NO           0           Normal
5     5  100000           20000            YES       50000           Salary
6     6  500000           25000            YES      200000           Salary
7     7  700000           35000            YES      400000        Bussiness
8     8    5000               0             NO           0           Normal
9     9   50000           10000             NO           0           Normal
10   10   60000           10000             NO           0           Normal
11   11   44545           13000             NO           0           Normal
12   12   20000           11000             NO           0           Normal
13   13   44545           20000            YES       50000           Salary
14   14   20000           25000            YES      200000           Salary
15   15  100000           35000            YES      400000        Bussiness
16   16    1000               0             NO           0  Student_account
17   17     500               0             NO           0  Student_account
18   18     NaN               0             NO           0  Student_account
19   19     NaN             NaN            NaN           0              NaN
20   20       0               0  not available        1200              NaN

# Common Features 

In [6]:
import pandas as pd
s5=pd.read_csv("bank_loan.csv")
#print(s5)
#print(s5.info())  # information in our DataFrame 
#fst 5 rows show
#print(s5.head())  # head(3)
# last 5 rows show
#print(s5.tail())  # tail(3)
#set data type of any column 
#s6=pd.read_csv("bank_loan.csv",dtype={'id':'float','Loan_Limit':'float'})
#print(s6)
# yes and no convert into True and False  but mention all the string like yes no and not available also inclue
s7=pd.read_csv("bank_loan.csv",true_values=["YES"],false_values=["NO","not available"])
#maximum rows in our data freame 
#print(pd.options.display.max_rows)   # how many rows in out DataFrame 
#duplicate value find 
#print(s5['Balnc'].duplicated()) # duplicate value include so return False 
#drop Duplicate Values 
#s5.drop_duplicates(inplace = True) inplace=True means !create another dataframe directly effect on s5

# Value Counts(how many times value repeat count)
#value count
#s5['Balnc'].value_counts()

#delete multiple row 
#s6=s5.drop([1,2,3],axis=0) # perticular row del
#delete column from s5 object 
#s7=s5.drop('Loan_Eli',axis=1) #delete column 





own function create and apply some calculation pertucular column 


In [7]:
s3=pd.read_csv("bank_loan.csv")
print(s3)
# apply method use 
def h(s):
    return s - 10
s4=s3[['Balnc']].apply(h)
s4




    id     Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
0    1   50000.0         10000.0             NO           0           Normal
1    2   60000.0         10000.0             NO           0           Normal
2    3   44545.0         13000.0             NO           0           Normal
3    4   20000.0         11000.0             NO           0           Normal
4    5  100000.0         20000.0            YES       50000           Salary
5    6  500000.0         25000.0            YES      200000           Salary
6    7  700000.0         35000.0            YES      400000        Bussiness
7    8    5000.0             0.0             NO           0           Normal
8    9   50000.0         10000.0             NO           0           Normal
9   10   60000.0         10000.0             NO           0           Normal
10  11   44545.0         13000.0             NO           0           Normal
11  12   20000.0         11000.0             NO           0           Normal

Balnc
0    49990.0
1    59990.0
2    44535.0
3    19990.0
4    99990.0
5   499990.0
6   699990.0
7     4990.0
8    49990.0
9    59990.0
10   44535.0
11   19990.0
12   44535.0
13   19990.0
14   99990.0
15     990.0
16     490.0
17       NaN
18       NaN
19     -10.0

In [17]:
import ipywidgets  as wid
s3=pd.read_csv("bank_loan.csv")
def xy(x=''):
    if x:
        y=int(x)
        rslt_df = s3[s3['Balnc'] > y]
        print(rslt_df)
wid.interact(xy,x='')    

interactive(children=(Text(value='', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.xy(x='')>

# # Perticular row show condition basis 

In [8]:
s3=pd.read_csv("bank_loan.csv")
#rslt_df = s3[s3['Balnc'] > 80000]
#print('\nResult dataframe :\n', rslt_df)
    
    
# selecting rows based on condition
options = ['Student_account', 'Bussiness']
rslt_df1 = s3[s3['Act_type'].isin(options)]
# 'Student_account', 'Bussiness' wise show row 
print('\nResult dataframe :\n', rslt_df1)
#Selecting all the rows from the given dataframe in which ‘Act_type’ is not present in the options list using .loc[].
#options = ['Student_account', 'Bussiness']
# !'Student_account', 'Bussiness' wise show row 
#rslt_df2 = s3.loc[~s3['Act_type'].isin(options)]
#print('\nResult dataframe :\n', rslt_df2)

#rslt_df3 = s3[(s3['Balnc'] == 100000) & s3['Monthly_Credit']==20000]
#print('\nResult dataframe :\n', rslt_df3)

# Data Short ASC order
#s3.sort_values(by=['Balnc'],ascending=False)





Result dataframe :
     id     Balnc  Monthly_Credit Loan_Eli  Loan_Limit         Act_type
6    7  700000.0         35000.0      YES      400000        Bussiness
14  15  100000.0         35000.0      YES      400000        Bussiness
15  16    1000.0             0.0       NO           0  Student_account
16  17     500.0             0.0       NO           0  Student_account
17  18       NaN             0.0       NO           0  Student_account


# Perticular Column Convert into DateTime 


In [9]:
s3=pd.read_csv("bank_loan.csv")

s4['id'] = pd.to_datetime(s3['id'])

print(s4['id'])

0    1970-01-01 00:00:00.000000001
1    1970-01-01 00:00:00.000000002
2    1970-01-01 00:00:00.000000003
3    1970-01-01 00:00:00.000000004
4    1970-01-01 00:00:00.000000005
5    1970-01-01 00:00:00.000000006
6    1970-01-01 00:00:00.000000007
7    1970-01-01 00:00:00.000000008
8    1970-01-01 00:00:00.000000009
9    1970-01-01 00:00:00.000000010
10   1970-01-01 00:00:00.000000011
11   1970-01-01 00:00:00.000000012
12   1970-01-01 00:00:00.000000013
13   1970-01-01 00:00:00.000000014
14   1970-01-01 00:00:00.000000015
15   1970-01-01 00:00:00.000000016
16   1970-01-01 00:00:00.000000017
17   1970-01-01 00:00:00.000000018
18   1970-01-01 00:00:00.000000019
19   1970-01-01 00:00:00.000000020
Name: id, dtype: datetime64[ns]


# Handle Missing Value (Pandas)

In [13]:
# show NaN for missing value or null

#s5=pd.read_csv("bank_loan.csv")
#print(s5)
# not available','no values' string include in your column  replace with NaN 
#s6=pd.read_csv("bank_loan.csv",na_values=['not available','no values'])
#print(s6)
#perticular column value define as a NaN
#s7=pd.read_csv("bank_loan.csv",na_values={'Loan_Eli':'NO'})
#print(s7)
#if do not fill ur column as a NaN 
#s8=pd.read_csv("bank_loan.csv",keep_default_na=False)
#print(s8)
#missing value fill NaN na_filter=True  or False
s9=pd.read_csv("bank_loan.csv",na_filter=True)
print(s9)



    id     Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
0    1   50000.0         10000.0             NO           0           Normal
1    2   60000.0         10000.0             NO           0           Normal
2    3   44545.0         13000.0             NO           0           Normal
3    4   20000.0         11000.0             NO           0           Normal
4    5  100000.0         20000.0            YES       50000           Salary
5    6  500000.0         25000.0            YES      200000           Salary
6    7  700000.0         35000.0            YES      400000        Bussiness
7    8    5000.0             0.0             NO           0           Normal
8    9   50000.0         10000.0             NO           0           Normal
9   10   60000.0         10000.0             NO           0           Normal
10  11   44545.0         13000.0             NO           0           Normal
11  12   20000.0         11000.0             NO           0           Normal

Finding missing Value 

In [17]:
s9=pd.read_csv("bank_loan.csv")
#missing value return true & otherwise False 
#print(s9.isnull())
#column wise null value count
#print(s9.isnull().sum())
#Total null value count
#print(s9.isnull().sum().sum())

# not missing value return true & otherwise False 
#print(s9.notnull())
#column wise not null value count
#print(s9.notnull().sum())
#Total not null value count
#print(s9.notnull().sum().sum())

      id  Balnc  Monthly_Credit  Loan_Eli  Loan_Limit  Act_type
0   True   True            True      True        True      True
1   True   True            True      True        True      True
2   True   True            True      True        True      True
3   True   True            True      True        True      True
4   True   True            True      True        True      True
5   True   True            True      True        True      True
6   True   True            True      True        True      True
7   True   True            True      True        True      True
8   True   True            True      True        True      True
9   True   True            True      True        True      True
10  True   True            True      True        True      True
11  True   True            True      True        True      True
12  True   True            True      True        True      True
13  True   True            True      True        True      True
14  True   True            True      Tru

DropNa() function use = drop missing value

In [7]:
s9=pd.read_csv("bank_loan.csv")
#print(s9)
#if missing or NaN value include drop this column or Row
#s10=s9.dropna(axis=1) # axis=1 for column 
#print(s10)
#s11=s9.dropna(how='any') # any = default NaN include del this row , all= all value are NaN then del the row
#print(s11)
#s12=s9.dropna(thresh=3) # minimum 3 not NaN value include column print   
#print(s12)
#s13=s9.dropna(subset=['Balnc']) #  Nan value del on perticular column wise  
#print(s13)
#s9.dropna(inplace=True) # do not create another dataframe update mother data frame  so, !write s9=s9.dropna()
#print(s9)

fillna() function use=fillna the NaN values with given values (input)

In [18]:
s9=pd.read_csv("bank_loan.csv")
#NaN value replace with 0 or any value 
#s10=s9.fillna(0)
#print(s10)
#specific column wise choice value input
#s11=s9.fillna({'Balnc':0,'Act_type':'ABC'})
#print(s11)
#previous row value fill replace  NaN value 
#s12=s9.fillna(method='ffill')  # bfill next value 
#print(s12)
#previous column value fill replace  NaN value 
#s13=s9.fillna(method='ffill',axis=1)  # axis=0 row value fill
#print(s13)
#only one NaN value fill with 0 every column 
#s14=s9.fillna(0,limit=1)  # limit = choose your value 
#print(s14)
#perticular column NaN value replace 
#s9["Balnc"].fillna(130, inplace = True)

#print(s9)

Replace function use ( values to the dataframe are replaced with other values dynamically) 

In [28]:
s9=pd.read_csv("bank_loan.csv")
#repalce value to value 
#s10=s9.replace(to_replace='NO',value='x') #s10=s9.replace('NO','x')  bcz fst and 2nd parameter 
#print(s10)
#different differrent value repalce with perticuar value ( your id column follow)
#s11=s9.replace(to_replace=[1,2,3,4],value=20) # values=[20,21,22,23]
#print(s11)
# pericular column value  replace 
#s12=s9.replace({'Act_type':'Normal'},value='NO') 
#print(s12)
#regula expression through use our replace function 
#s13=s9.replace('[A-Za-z]',0,regex=True) 
#print(s13)

# pericular column value  regular expression use 
#s14=s9.replace({'Act_type':'[a-zA-Z]'},0,regex=True) # values=[20,21,22,23]

#print(s14)

    id     Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
0    1   50000.0         10000.0             NO           0           Normal
1    2   60000.0         10000.0             NO           0           Normal
2    3   44545.0         13000.0             NO           0           Normal
3    4   20000.0         11000.0             NO           0           Normal
4    5  100000.0         20000.0            YES       50000           Salary
5    6  500000.0         25000.0            YES      200000           Salary
6    7  700000.0         35000.0            YES      400000        Bussiness
7    8    5000.0             0.0             NO           0           Normal
8    9   50000.0         10000.0             NO           0           Normal
9   10   60000.0         10000.0             NO           0           Normal
10  11   44545.0         13000.0             NO           0           Normal
11  12   20000.0         11000.0             NO           0           Normal

interpolate function is basically used to fill NAN values in dataframe or series 


In [37]:
s9=pd.read_csv("bank_loan.csv")
#print(s9)
#interpolate math calculation by-default linear part 
#s10=s9.interpolate(method='linear',direction='forord')
#print(s10)
#nearest value receive
#s10=s9.interpolate(method='nearest')
#print(s10)


    id     Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
0    1   50000.0         10000.0             NO           0           Normal
1    2   60000.0         10000.0             NO           0           Normal
2    3   44545.0         13000.0             NO           0           Normal
3    4   20000.0         11000.0             NO           0           Normal
4    5  100000.0         20000.0            YES       50000           Salary
5    6  500000.0         25000.0            YES      200000           Salary
6    7  700000.0         35000.0            YES      400000        Bussiness
7    8    5000.0             0.0             NO           0           Normal
8    9   50000.0         10000.0             NO           0           Normal
9   10   60000.0         10000.0             NO           0           Normal
10  11   44545.0         13000.0             NO           0           Normal
11  12   20000.0         11000.0             NO           0           Normal

pandas loc method ...Access a group of rows & columns by label or a boolean array 

In [38]:
s9=pd.read_csv("bank_loan.csv")
# show row 0 details 
#s9.loc[0] # list of rows [0,1,2]
# perticlar column & row value
#s9.loc[4,'Monthly_Credit'] 
#mention start point & end point 
#s9.loc[0:3]
#condition operator use 
#s9.loc[s9['Balnc']>10000]
#condition operator use & show perticular column  
#s9.loc[s9['Balnc']>10000,['Loan_Eli']]

pandas iloc method use --integer location-based indexing 


In [49]:
s9=pd.read_csv("bank_loan.csv")
#s9.iloc[0] #[1,2,3]
#s9.iloc[0:2]
# difference between s9.loc[0:4,'column_name']
s9.iloc[0:4,0] # 0 to 4 row value and column 0 index  


0    1
1    2
2    3
3    4
Name: id, dtype: int64

GroupBy Function use ..... is used to split the data into groups based on some criteria

In [52]:
s9=pd.read_csv("bank_loan.csv")
s10=s9.groupby('Act_type') # like SQL select * from table_name group by Act_type
#return a object 
#s10
#print s10 Object
for x,y in s10:
    print(x)
    print(y)

Bussiness
    id     Balnc  Monthly_Credit Loan_Eli  Loan_Limit   Act_type
6    7  700000.0         35000.0      YES      400000  Bussiness
14  15  100000.0         35000.0      YES      400000  Bussiness
Normal
    id    Balnc  Monthly_Credit Loan_Eli  Loan_Limit Act_type
0    1  50000.0         10000.0       NO           0   Normal
1    2  60000.0         10000.0       NO           0   Normal
2    3  44545.0         13000.0       NO           0   Normal
3    4  20000.0         11000.0       NO           0   Normal
7    8   5000.0             0.0       NO           0   Normal
8    9  50000.0         10000.0       NO           0   Normal
9   10  60000.0         10000.0       NO           0   Normal
10  11  44545.0         13000.0       NO           0   Normal
11  12  20000.0         11000.0       NO           0   Normal
Salary
    id     Balnc  Monthly_Credit Loan_Eli  Loan_Limit Act_type
4    5  100000.0         20000.0      YES       50000   Salary
5    6  500000.0         25000.0   

In [56]:
# just mention one value 
#s10.get_group('Normal') #like SQL select * from table_name group by Act_type where Act_type='Normal'
#maximum value return group wise 
#s10.max()
#describe my data details group wise 
#s10.describe()
#perticular function mentions 
s10.agg(['count','max'])

id     Balnc           Monthly_Credit          Loan_Eli  \
                count max count       max          count      max    count   
Act_type                                                                     
Bussiness           2  15     2  700000.0              2  35000.0        2   
Normal              9  12     9   60000.0              9  13000.0        9   
Salary              4  14     4  500000.0              4  25000.0        4   
Student_account     3  18     2    1000.0              3      0.0        3   

                     Loan_Limit          
                 max      count     max  
Act_type                                 
Bussiness        YES          2  400000  
Normal            NO          9       0  
Salary           YES          4  200000  
Student_account   NO          3       0

pandas marging function = SQL join concept

In [64]:
table1=pd.DataFrame({"name":['som','som2','som3','som4','som5','som6','som7'],"mks":[12,16,15,85,89,55,57]})
table2=pd.DataFrame({"name":['som','som2','som3','ab1','ab2','ab3','ab4'],"Sec":['A','A','A','B','B','B','B']})
#print(table1)
#print(table2)
#join 2 dataframe 
#s2=pd.merge(table1,table2,on='name',how='inner') #  on= 'common value' how='outer'/'right'/'left' rmation)
#print(s2)
#indicator=True left join right join both information provide 
#s2=pd.merge(table1,table2,on='name',how='outer',indicator=True) #  on= 'common value' how='outer'/'right'/'left' rmation)
#print(s2)
#join left column  and right column show
#s2=pd.merge(table1,table2,left_index=True,right_index=True) # name_x & nam_y change throuh suffixes=('_a','_b')
#s2


pandas Concat Function .(marge=one column name same but ! concat )

In [68]:
table1=pd.DataFrame({"name":['som','som2','som3','som4','som5','som6','som7'],"mks":[12,16,15,85,89,55,57]})
table2=pd.DataFrame({"name":['som','som2','som3','ab1'],"mks":[12,16,15,87]})
#concat two data frame 
#s=pd.concat([table1,table2])
#print(s)
#fst one data frame then other data frame 
#s=pd.concat([table1,table2],axis=1)
#print(s)
#index wise match bydefault 
#s=pd.concat([table1,table2],axis=1,join='inner') # compare index wise therefore show all data 
#print(s)


   name  mks  name  mks
0   som   12   som   12
1  som2   16  som2   16
2  som3   15  som3   15
3  som4   85   ab1   87


In [55]:
#change index then compare value 
table1=pd.DataFrame({"name":['som','som2','som3','som4','som5','som6','som7'],"mks":[12,16,15,85,89,55,57]},index=[1,2,3,4,5,6,7])
table2=pd.DataFrame({"name":['som','som2','som3','ab1'],"mks":[12,16,15,85]},index=[1,2,3,4])
#print(table1)
#print(table2)
#s=pd.concat([table1,table2],axis=1,join='inner') # compare index wise therefore show all data 
#print(s)

   name  mks  name  mks
1   som   12   som   12
2  som2   16  som2   16
3  som3   15  som3   15
4  som4   85   ab1   85


join = different column name join  

In [37]:
table1=pd.DataFrame({"name":['som','som2','som3'],"mks":[12,16,15]},index=[1,2,3])
table2=pd.DataFrame({"name1":['som','som2','som3'],"mks1":[12,16,15]})
display(table1,table2)
table1.join(table2)

name  mks
1   som   12
2  som2   16
3  som3   15

name1  mks1
0   som    12
1  som2    16
2  som3    15

name  mks name1  mks1
1   som   12  som2  16.0
2  som2   16  som3  15.0
3  som3   15   NaN   NaN

Append=datafame row join to another data frame 

In [71]:

table1=pd.DataFrame({"name":['som','som2','som3'],"mks":[12,16,15]},index=[1,2,3])
table2=pd.DataFrame({"name":['som','som2','som3'],"mks":[12,16,15]})
display(table1,table2)
#table 1 row join to table2(( ! column wise)) row but column name must same  if not same show NAN for not match value 
#table1.append(table2)
#index show orderly 
table1.append(table2,ignore_index=True)


name  mks
1   som   12
2  som2   16
3  som3   15

name1  mks1
0   som    12
1  som2    16
2  som3    15

name   mks name1  mks1
0   som  12.0   NaN   NaN
1  som2  16.0   NaN   NaN
2  som3  15.0   NaN   NaN
3   NaN   NaN   som  12.0
4   NaN   NaN  som2  16.0
5   NaN   NaN  som3  15.0

# Pivot Table 

In [74]:
s3=pd.read_csv("piv.csv")
#print(s3)
#pivot table create Acccount type wise every column mean value show 
#s4=s3.pivot_table(index='Act_type') #bydefault mean value show 
#print(s4)
#acount type and year wise grouping 
#s5=s3.pivot_table(index='Act_type',columns='year') #bydefault mean value show 
#print(s5)
#different function use in my pivot table 
#s6=s3.pivot_table(index='Act_type',columns='year',aggfunc='count') #bydefault mean value show 
#print(s6)
#Nan value replace with 0 
#s7=s3.pivot_table(index='Act_type',columns='year',aggfunc='count',fill_value=0) #bydefault mean value show 
#print(s7)

                Balnc                Loan_Eli                Loan_Limit       \
year             2010 2012 2015 2018     2010 2012 2015 2018       2010 2012   
Act_type                                                                       
Bussiness         NaN  1.0  NaN  1.0      NaN  1.0  NaN  1.0        NaN  1.0   
Normal            4.0  1.0  4.0  NaN      4.0  1.0  4.0  NaN        4.0  1.0   
Salary            NaN  2.0  NaN  2.0      NaN  2.0  NaN  2.0        NaN  2.0   
Student_account   NaN  NaN  NaN  2.0      NaN  NaN  NaN  3.0        NaN  NaN   

                          Monthly_Credit                  id                 
year            2015 2018           2010 2012 2015 2018 2010 2012 2015 2018  
Act_type                                                                     
Bussiness        NaN  1.0            NaN  1.0  NaN  1.0  NaN  1.0  NaN  1.0  
Normal           4.0  NaN            4.0  1.0  4.0  NaN  4.0  1.0  4.0  NaN  
Salary           NaN  2.0            NaN  2.0  Na

# Mean(Average) Value Find 

In [69]:
import numpy as np
s3=pd.read_csv("bank_loan.csv")
x = s3["Balnc"].mean()   #median()      
s3["Balnc"].fillna(x, inplace = True)
print(s3)
#s3.head(2)
#s3["Balnc"] = s3["Balnc"].replace(np.nan, x)
#print(s3["Balnc"])
#s3["Balnc"]=s3["Balnc"].fillna(x)
#print(s3["Balnc"])

    id     Balnc  Monthly_Credit       Loan_Eli  Loan_Limit         Act_type
0    1   50000.0         10000.0             NO           0           Normal
1    2   60000.0         10000.0             NO           0           Normal
2    3   44545.0         13000.0             NO           0           Normal
3    4   20000.0         11000.0             NO           0           Normal
4    5  100000.0         20000.0            YES       50000           Salary
5    6  500000.0         25000.0            YES      200000           Salary
6    7  700000.0         35000.0            YES      400000        Bussiness
7    8    5000.0             0.0             NO           0           Normal
8    9   50000.0         10000.0             NO           0           Normal
9   10   60000.0         10000.0             NO           0           Normal
10  11   44545.0         13000.0             NO           0           Normal
11  12   20000.0         11000.0             NO           0           Normal

# Median = the value in the middle, after you have sorted all values ascending.
[5,9,8,12,1,6] = 1,5,6,8,9,12 = (6+8)/2=7

In [69]:
s=pd.Series([5,9,8,12,1,6])
print(s.median())

7.0


In [71]:
s3=pd.read_csv("bank_loan.csv")
x = s3["Balnc"].median()
print(x)
s3["Balnc"].fillna(x, inplace = True)
s3.head(2)

44545.0


id    Balnc  Monthly_Credit Loan_Eli  Loan_Limit Act_type
0   1  50000.0         10000.0       NO           0   Normal
1   2  60000.0         10000.0       NO           0   Normal

# Mode ( Maximum repeat value(small value ) return 

In [70]:
s=pd.Series([21, 19, 18, 46, 30, 17, 19, 21, 18]) #([[19, 21, 18, 30, 46]])
print(s.mode())
print(s.mode()[0])

0    18
1    19
2    21
dtype: int64
18


In [ ]:
x = s3["Balnc"].mode()[0]
x
s3["Balnc"].fillna(x, inplace = True)


# Standard deviation

In [ ]:
x = s3["Balnc"].std()
x
s3["Balnc"].fillna(x, inplace = True)


# Statistic Operation

In [ ]:
# import statistics
 
# initializing list
li = [1, 2, 3, 3, 2,6]
 
# using mean() to calculate average of list
# elements
print ("The average of list values is : ",end="")
print (statistics.mean(li))

# #Median value find

In [ ]:
print (statistics.median(li))

# #Median_low value find()

In [ ]:
print (statistics.median_low(li))

# #Median_high  value find()

In [ ]:

print (statistics.median_high(li))

# #Mode  value find()

In [ ]:

print (statistics.mode(li))

# #Range Find (maximum value - minimum value )

In [ ]:
print (max(li)-min(li))

# Mean Diviation(by mean)

In [ ]:
from numpy import mean, absolute
  
data = [1,2,3,4,5]
  
# Absolute mean deviation
print(mean(absolute(data - mean(data))))

In [ ]:

sample = [17, 15, 23, 7, 9,13]
print(statistics.variance(sample))

In [ ]:
print(statistics.stdev(sample))